version: "3.9"

services:
  backend:
    build: ./backend
    container_name: credit-jambo-client-backend
    restart: always
    ports:
      - "5002:5000"
    env_file:
      - ./backend/.env
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/credit_jambo
    extra_hosts:
      - "db:host-gateway"
