services:
  backend:
    build: ./backend
    container_name: credit-jambo-client-backend
    restart: always
    ports:
      - "5002:5002"
    env_file:
      - ./backend/.env
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/credit_jambo
    networks:
      - credit-jambo-admin_shared-db-network

  client-frontend:
    build: ./frontend
    container_name: credit-jambo-client-frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_CLIENT_API: http://localhost:5002/api
    depends_on:
      - backend
    networks:
      - credit-jambo-admin_shared-db-network

networks:
  credit-jambo-admin_shared-db-network:
    external: true
