version: "3.9"

services:
  backend:
    build: ./backend
    container_name: credit-jambo-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      # Ensures your app can reach the DB by service name
      DB_URL: postgres://postgres:postgres@db:5432/credit_jambo
    command: npm run dev # Optional override if needed
  db:
    image: postgres:15
    container_name: credit-jambo-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credit_jambo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
